### ISSUE TITLE
Bean has no getName() method

### ISSUE THREAD

**Issue by pbauermeister** [PunchThrough/Bean-Android-SDK#3]
Hi, as of now (*) I could not find the `getName()` method, that is mentioned in the §"List nearby Bean(s)" of `README.md`. Did I miss anything?

Thanks for any help.

(*) commit ebff765d9c45a3fbd4fb20d404c0d4b18a718d8e

**Comment by swstack** [comment]
Hi @pbauermeister , thanks for reporting this issue!  You are absolutely correct about the `getName()` method being missing on the `Bean` ... I will have it fixed today.

**Comment by swstack** [comment]
This PR updates README, will get merged soon, https://github.com/PunchThrough/Bean-Android-SDK/pull/4

**Comment by swstack** [comment]
@pbauermeister the README has been updated, please let us know if you have any other issues!

**Comment by pbauermeister** [comment]
With the fixed README, now I get my app to build and work as expected. Thanks for your prompt support!
