### ISSUE TITLE
Thread.sleep() in docs for connecting the Bean

### ISSUE THREAD

**Issue by hvisser** [PunchThrough/Bean-Android-SDK#6]
The README states to use `Thread.sleep()` for a connection, but this is ill advised: it will lock up the main thread, making the app hang and technically there's no guarantee that the device will be connected in 5 seconds. In practice calls to the Bean should only be made after a succesfull `onConnected` call.

**Comment by swstack** [comment]
Hey @hvisser I am real sorry about the delayed reply.  My original goal with the README was to show off API usage, not necessarily best practice, however you are absolutely correct and I've updated the README to reflect your feedback!  Thanks.
